### ISSUE TITLE
Save model

### ISSUE THREAD

**Issue by YoshikiMas** [ken-nag/recursive_separation#1]
https://github.com/ken-nag/recursive_separation/blob/1ab8e4f87c15dd5fa1e812eeb73177f95428fc4d/wave_u_net/train_inst_num_2.py#L42

ここ’/’じゃなくて'%'では？

**Comment by ken-nag** [comment]
Thanks pointing out.
Enikaita gomi code de Kuso warota.
@YoshikiMas
